site_name: ndi-matlab
repo_url: https://github.com/VH-Lab/NDI-matlab
site_author: Steve Van Hooser
docs_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: 'deep-purple'
    accent: 'deep-purple'
pages:
  - Home: index.md
  - The NDI model:
    - Introduction: ndimodel/1_intro.md
    - Real world vocabulary: ndimodel/2_ndimodel_vocabulary.md

use_directory_urls: true

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
  - toc:
      permalink: true
  - codehilite

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML']

