site_name: ndi-matlab
repo_url: https://github.com/VH-Lab/NDI-matlab
site_author: Steve Van Hooser
docs_dir: 'docs'
theme:
  name: 'mkdocs'
  palette:
    primary: 'deep-purple'
    accent: 'deep-purple'
pages:
  - Home: index.md
  - The NDI model:
    - Introduction: 'ndimodel/1_intro.md'
    - Real world vocabulary: 'ndimodel/2_ndimodel_vocabulary.md'

use_directory_urls: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite


