site_name: NDI-matlab
repo_url: https://github.com/VH-Lab/NDI-matlab
site_author: Steve Van Hooser
docs_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: 'deep-purple'
    accent: 'deep-purple'
  features:
    - navigation.expand
nav:
  - Home: index.md
  - Installation: 'installation.md'
  - Tutorials:
    - The NDI model:
      - Introduction: 'ndimodel/1_intro.md'
      - Real world vocabulary: 'ndimodel/2_ndimodel_vocabulary.md'
    - Planned soon:
      - Analyzing your first electrophysiology experiment with NDI: 'tutorials/analyzing_first_physiology_experiment.md'
      - Reading your own data in NDI: 'tutorials/reading_own_data_ndi.md'
      - Case studies in reading data in NDI: 'tutorials/case_studies_reading_data.md'
      - Making your own data pipeline in NDI: 'tutorials/data_pipeline.md'
      - Making your own analysis app that uses NDI: 'tutorials/analysis_app.md'
    - Planned later:
      - Submitting your data to an archive: 'tutorials/archive.md'
      - Search and analyze NDI databases on the web: 'tutorials/search_ndi_databases.md'
  - Document reference:
    - ndi_document : 'documents/ndi_document.md'
    - ndi_document_animalsubject : 'documents/ndi_document_animalsubject.md'
    - ndi_document_app : 'documents/ndi_document_app.md'
    - ndi_document_element : 'documents/ndi_document_element.md'
    - ndi_document_element_epoch : 'documents/ndi_document_element_epoch.md'
    - ndi_document_epochid : 'documents/ndi_document_epochid.md'
    - ndi_document_projectvar : 'documents/ndi_document_projectvar.md'
    - ndi_document_subject : 'documents/ndi_document_subject.md'
    - ndi_document_subjectmeasurement : 'documents/ndi_document_subjectmeasurement.md'
    - apps:
      - jrclust:
        - jrclust_clusters : 'documents/apps/jrclust/jrclust_clusters.md'
      - markgarbage:
        - valid_interval : 'documents/apps/markgarbage/valid_interval.md'
      - spikeextractor:
        - spike_extraction_parameters : 'documents/apps/spikeextractor/spike_extraction_parameters.md'
        - spike_extraction_parameters_modification : 'documents/apps/spikeextractor/spike_extraction_parameters_modification.md'
        - spiketimes : 'documents/apps/spikeextractor/spiketimes.md'
        - spikewaves : 'documents/apps/spikeextractor/spikewaves.md'
      - spikesorter:
        - sorting_parameters : 'documents/apps/spikesorter/sorting_parameters.md'
        - spike_clusters : 'documents/apps/spikesorter/spike_clusters.md'
      - spikesorter_hengen:
        - extraction_parameters : 'documents/apps/spikesorter_hengen/extraction_parameters.md'
        - mountainsort_parameters : 'documents/apps/spikesorter_hengen/mountainsort_parameters.md'
        - neuron_hengen : 'documents/apps/spikesorter_hengen/neuron_hengen.md'
        - probe_geometry : 'documents/apps/spikesorter_hengen/probe_geometry.md'
      - vhlab_voltage2firingrate:
        - binnedspikeratevm : 'documents/apps/vhlab_voltage2firingrate/binnedspikeratevm.md'
        - vmneuralresponseresiduals : 'documents/apps/vhlab_voltage2firingrate/vmneuralresponseresiduals.md'
        - vmspikefilteringparameters : 'documents/apps/vhlab_voltage2firingrate/vmspikefilteringparameters.md'
        - vmspikefit : 'documents/apps/vhlab_voltage2firingrate/vmspikefit.md'
        - vmspikesummary : 'documents/apps/vhlab_voltage2firingrate/vmspikesummary.md'
    - daq:
      - ndi_document_daqmetadatareader : 'documents/daq/ndi_document_daqmetadatareader.md'
      - ndi_document_daqreader : 'documents/daq/ndi_document_daqreader.md'
      - ndi_document_daqsystem : 'documents/daq/ndi_document_daqsystem.md'
      - ndi_document_filenavigator : 'documents/daq/ndi_document_filenavigator.md'
      - ndi_document_syncgraph : 'documents/daq/ndi_document_syncgraph.md'
      - ndi_document_syncrule : 'documents/daq/ndi_document_syncrule.md'
    - data:
      - fitcurve : 'documents/data/fitcurve.md'
      - ndi_document_binaryseries : 'documents/data/ndi_document_binaryseries.md'
    - neuron:
      - neuron_extracellular : 'documents/neuron/neuron_extracellular.md'
    - newdoctemplate:
      - ndi_document_newdoctemplate : 'documents/newdoctemplate/ndi_document_newdoctemplate.md'
    - stimulus:
      - control_stimulus_ids : 'documents/stimulus/control_stimulus_ids.md'
      - stimulus_presentation : 'documents/stimulus/stimulus_presentation.md'
      - stimulus_response : 'documents/stimulus/stimulus_response.md'
      - stimulus_response_scalar : 'documents/stimulus/stimulus_response_scalar.md'
      - stimulus_response_scalar_parameters : 'documents/stimulus/stimulus_response_scalar_parameters.md'
      - stimulus_response_scalar_parameters_basic : 'documents/stimulus/stimulus_response_scalar_parameters_basic.md'
      - stimulus_tuningcurve : 'documents/stimulus/stimulus_tuningcurve.md'
      - vision:
        - oridir:
          - orientation_direction_tuning : 'documents/stimulus/vision/oridir/orientation_direction_tuning.md'
  - Code reference: 
    - ndi_Init: 'reference/ndi_Init.m.md'
    - ndi_install: 'reference/ndi_install.m.md'
    - ndi PACKAGE:
      - ndi.app: 'reference/+ndi/app.m.md'
      - ndi.cache: 'reference/+ndi/cache.m.md'
      - ndi.database: 'reference/+ndi/database.m.md'
      - ndi.document: 'reference/+ndi/document.m.md'
      - ndi.documentservice: 'reference/+ndi/documentservice.m.md'
      - ndi.element: 'reference/+ndi/element.m.md'
      - ndi.filesep: 'reference/+ndi/filesep.m.md'
      - ndi.globals: 'reference/+ndi/globals.m.md'
      - ndi.ido: 'reference/+ndi/ido.m.md'
      - ndi.neuron: 'reference/+ndi/neuron.m.md'
      - ndi.probe: 'reference/+ndi/probe.m.md'
      - ndi.query: 'reference/+ndi/query.m.md'
      - ndi.session: 'reference/+ndi/session.m.md'
      - ndi.subject: 'reference/+ndi/subject.m.md'
      - ndi.validate: 'reference/+ndi/validate.m.md'
      - ndi.version: 'reference/+ndi/version.m.md'
      - app PACKAGE:
        - ndi.app.appdoc: 'reference/+ndi/+app/appdoc.m.md'
        - ndi.app.markgarbage: 'reference/+ndi/+app/markgarbage.m.md'
        - ndi.app.oridirtuning: 'reference/+ndi/+app/oridirtuning.m.md'
        - ndi.app.spikeextractor: 'reference/+ndi/+app/spikeextractor.m.md'
        - ndi.app.spikesorter: 'reference/+ndi/+app/spikesorter.m.md'
        - ndi.app.spikesorter_hengen: 'reference/+ndi/+app/spikesorter_hengen.m.md'
        - stimulus PACKAGE:
          - ndi.app.stimulus.decoder: 'reference/+ndi/+app/+stimulus/decoder.m.md'
          - ndi.app.stimulus.tuning_response: 'reference/+ndi/+app/+stimulus/tuning_response.m.md'
      - daq PACKAGE:
        - ndi.daq.daqsystemstring: 'reference/+ndi/+daq/daqsystemstring.m.md'
        - ndi.daq.metadatareader: 'reference/+ndi/+daq/metadatareader.m.md'
        - ndi.daq.reader: 'reference/+ndi/+daq/reader.m.md'
        - ndi.daq.system: 'reference/+ndi/+daq/system.m.md'
        - metadata PACKAGE:
          - ndi.daq.metadata.epochprobemap_daqsystem: 'reference/+ndi/+daq/+metadata/epochprobemap_daqsystem.m.md'
          - ndi.daq.metadata.epochprobemap_daqsystem_vhlab: 'reference/+ndi/+daq/+metadata/epochprobemap_daqsystem_vhlab.m.md'
        - metadatareader PACKAGE:
          - ndi.daq.metadatareader.AngelucciStims: 'reference/+ndi/+daq/+metadatareader/AngelucciStims.m.md'
          - ndi.daq.metadatareader.NewStimStims: 'reference/+ndi/+daq/+metadatareader/NewStimStims.m.md'
        - reader PACKAGE:
          - ndi.daq.reader.mfdaq: 'reference/+ndi/+daq/+reader/mfdaq.m.md'
          - mfdaq PACKAGE:
            - ndi.daq.reader.mfdaq.blackrock: 'reference/+ndi/+daq/+reader/+mfdaq/blackrock.m.md'
            - ndi.daq.reader.mfdaq.cedspike2: 'reference/+ndi/+daq/+reader/+mfdaq/cedspike2.m.md'
            - ndi.daq.reader.mfdaq.intan: 'reference/+ndi/+daq/+reader/+mfdaq/intan.m.md'
            - ndi.daq.reader.mfdaq.spikegadgets: 'reference/+ndi/+daq/+reader/+mfdaq/spikegadgets.m.md'
            - stimulus PACKAGE:
              - ndi.daq.reader.mfdaq.stimulus.angelucci_visstim: 'reference/+ndi/+daq/+reader/+mfdaq/+stimulus/angelucci_visstim.m.md'
              - ndi.daq.reader.mfdaq.stimulus.vhlabvisspike2: 'reference/+ndi/+daq/+reader/+mfdaq/+stimulus/vhlabvisspike2.m.md'
        - system PACKAGE:
          - ndi.daq.system.mfdaq: 'reference/+ndi/+daq/+system/mfdaq.m.md'
      - data PACKAGE:
        - ndi.data.evaluate_fitcurve: 'reference/+ndi/+data/evaluate_fitcurve.m.md'
      - database PACKAGE:
        - ndi.database.binarydoc: 'reference/+ndi/+database/binarydoc.m.md'
        - fun PACKAGE:
          - ndi.database.fun.createGenBankControlledVocabulary: 'reference/+ndi/+database/+fun/createGenBankControlledVocabulary.m.md'
          - ndi.database.fun.createNIFbrainareas: 'reference/+ndi/+database/+fun/createNIFbrainareas.m.md'
          - ndi.database.fun.databasehierarchyinit: 'reference/+ndi/+database/+fun/databasehierarchyinit.m.md'
          - ndi.database.fun.docs2graph: 'reference/+ndi/+database/+fun/docs2graph.m.md'
          - ndi.database.fun.findalldependencies: 'reference/+ndi/+database/+fun/findalldependencies.m.md'
          - ndi.database.fun.finddocs_missing_dependencies: 'reference/+ndi/+database/+fun/finddocs_missing_dependencies.m.md'
          - ndi.database.fun.ndi_document2ndi_object: 'reference/+ndi/+database/+fun/ndi_document2ndi_object.m.md'
          - ndi.database.fun.opendatabase: 'reference/+ndi/+database/+fun/opendatabase.m.md'
          - ndi.database.fun.plotinteractivedocgraph: 'reference/+ndi/+database/+fun/plotinteractivedocgraph.m.md'
          - ndi.database.fun.projectvardef: 'reference/+ndi/+database/+fun/projectvardef.m.md'
          - ndi.database.fun.readGenBankNames: 'reference/+ndi/+database/+fun/readGenBankNames.m.md'
          - ndi.database.fun.readGenBankNodes: 'reference/+ndi/+database/+fun/readGenBankNodes.m.md'
        - implementations PACKAGE:
          - binarydoc PACKAGE:
            - ndi.database.implementations.binarydoc.matfid: 'reference/+ndi/+database/+implementations/+binarydoc/matfid.m.md'
          - database PACKAGE:
            - ndi.database.implementations.database.matlabdumbjsondb: 'reference/+ndi/+database/+implementations/+database/matlabdumbjsondb.m.md'
            - ndi.database.implementations.database.postgresdb: 'reference/+ndi/+database/+implementations/+database/postgresdb.m.md'
      - element PACKAGE:
        - ndi.element.timeseries: 'reference/+ndi/+element/timeseries.m.md'
      - epoch PACKAGE:
        - ndi.epoch.epochprobemap: 'reference/+ndi/+epoch/epochprobemap.m.md'
        - ndi.epoch.epochset: 'reference/+ndi/+epoch/epochset.m.md'
        - ndi.epoch.findepochnode: 'reference/+ndi/+epoch/findepochnode.m.md'
        - epochset PACKAGE:
          - ndi.epoch.epochset.param: 'reference/+ndi/+epoch/+epochset/param.m.md'
      - file PACKAGE:
        - ndi.file.navigator: 'reference/+ndi/+file/navigator.m.md'
        - navigator PACKAGE:
          - ndi.file.navigator.epochdir: 'reference/+ndi/+file/+navigator/epochdir.m.md'
      - fun PACKAGE:
        - ndi.fun.convertoldnsd2ndi: 'reference/+ndi/+fun/convertoldnsd2ndi.m.md'
        - ndi.fun.stimulustemporalfrequency: 'reference/+ndi/+fun/stimulustemporalfrequency.m.md'
      - gui PACKAGE:
        - ndi.gui.Data: 'reference/+ndi/+gui/Data.m.md'
        - ndi.gui.Icon: 'reference/+ndi/+gui/Icon.m.md'
        - ndi.gui.Lab: 'reference/+ndi/+gui/Lab.m.md'
        - ndi.gui.gui: 'reference/+ndi/+gui/gui.m.md'
        - ndi.gui.gui_v2: 'reference/+ndi/+gui/gui_v2.m.md'
      - neuron PACKAGE:
        - ndi.neuron.hengen: 'reference/+ndi/+neuron/hengen.m.md'
      - probe PACKAGE:
        - ndi.probe.timeseries: 'reference/+ndi/+probe/timeseries.m.md'
        - fun PACKAGE:
          - ndi.probe.fun.probestruct2probe: 'reference/+ndi/+probe/+fun/probestruct2probe.m.md'
          - ndi.probe.fun.probetype2objectinit: 'reference/+ndi/+probe/+fun/probetype2objectinit.m.md'
        - timeseries PACKAGE:
          - ndi.probe.timeseries.mfdaq: 'reference/+ndi/+probe/+timeseries/mfdaq.m.md'
          - ndi.probe.timeseries.stimulator: 'reference/+ndi/+probe/+timeseries/stimulator.m.md'
      - session PACKAGE:
        - ndi.session.dir: 'reference/+ndi/+session/dir.m.md'
        - ndi.session.sessiontable: 'reference/+ndi/+session/sessiontable.m.md'
      - setups PACKAGE:
        - ndi.setups.angeluccilab_expdir: 'reference/+ndi/+setups/angeluccilab_expdir.m.md'
        - ndi.setups.angeluccilab_makedev: 'reference/+ndi/+setups/angeluccilab_makedev.m.md'
        - ndi.setups.katzlab_expdir: 'reference/+ndi/+setups/katzlab_expdir.m.md'
        - ndi.setups.katzlab_makedev: 'reference/+ndi/+setups/katzlab_makedev.m.md'
        - ndi.setups.marderlab_expdir: 'reference/+ndi/+setups/marderlab_expdir.m.md'
        - ndi.setups.marderlab_makedev: 'reference/+ndi/+setups/marderlab_makedev.m.md'
        - ndi.setups.vhlab_expdir: 'reference/+ndi/+setups/vhlab_expdir.m.md'
        - ndi.setups.vhlab_makedev: 'reference/+ndi/+setups/vhlab_makedev.m.md'
      - test PACKAGE:
        - ndi.test.cache: 'reference/+ndi/+test/cache.m.md'
        - app PACKAGE:
          - ndi.test.app.markgarbage: 'reference/+ndi/+test/+app/markgarbage.m.md'
          - ndi.test.app.spikeextractor: 'reference/+ndi/+test/+app/spikeextractor.m.md'
        - daq PACKAGE:
          - ndi.test.daq.blackrock: 'reference/+ndi/+test/+daq/blackrock.m.md'
          - ndi.test.daq.build_intan_flat_exp: 'reference/+ndi/+test/+daq/build_intan_flat_exp.m.md'
          - ndi.test.daq.intan_flat: 'reference/+ndi/+test/+daq/intan_flat.m.md'
          - ndi.test.daq.intan_flat_metadata: 'reference/+ndi/+test/+daq/intan_flat_metadata.m.md'
          - ndi.test.daq.intan_flat_saved: 'reference/+ndi/+test/+daq/intan_flat_saved.m.md'
          - ndi.test.daq.sg_flat: 'reference/+ndi/+test/+daq/sg_flat.m.md'
          - ndi.test.daq.test_ndi_device_image_tiffstack: 'reference/+ndi/+test/+daq/test_ndi_device_image_tiffstack.m.md'
          - ndi.test.daq.test_ndi_image_tiffstack_multipleepoch: 'reference/+ndi/+test/+daq/test_ndi_image_tiffstack_multipleepoch.m.md'
        - database PACKAGE:
          - ndi.test.database.test_ndi_document: 'reference/+ndi/+test/+database/test_ndi_document.m.md'
          - ndi.test.database.test_ndi_document_jsons: 'reference/+ndi/+test/+database/test_ndi_document_jsons.m.md'
          - ndi.test.database.test_ndi_validate: 'reference/+ndi/+test/+database/test_ndi_validate.m.md'
          - ndi.test.database.testpostgresdb: 'reference/+ndi/+test/+database/testpostgresdb.m.md'
          - ndi.test.database.testpostgresdb2: 'reference/+ndi/+test/+database/testpostgresdb2.m.md'
          - ndi.test.database.testpostgresdbsearch: 'reference/+ndi/+test/+database/testpostgresdbsearch.m.md'
          - core PACKAGE:
            - ndi.test.database.core.test_ndi_daq_documents: 'reference/+ndi/+test/+database/+core/test_ndi_daq_documents.m.md'
            - ndi.test.database.core.test_ndi_daqreader_documents: 'reference/+ndi/+test/+database/+core/test_ndi_daqreader_documents.m.md'
            - ndi.test.database.core.test_ndi_daqsystem_documents: 'reference/+ndi/+test/+database/+core/test_ndi_daqsystem_documents.m.md'
            - ndi.test.database.core.test_ndi_filenavigator_documents: 'reference/+ndi/+test/+database/+core/test_ndi_filenavigator_documents.m.md'
            - ndi.test.database.core.test_ndi_syncgraph_documents: 'reference/+ndi/+test/+database/+core/test_ndi_syncgraph_documents.m.md'
            - ndi.test.database.core.test_ndi_syncrule_documents: 'reference/+ndi/+test/+database/+core/test_ndi_syncrule_documents.m.md'
        - debug PACKAGE:
          - ndi.test.debug.ndi_debug_database_stats: 'reference/+ndi/+test/+debug/ndi_debug_database_stats.m.md'
        - element PACKAGE:
          - ndi.test.element.test_ndi_element: 'reference/+ndi/+test/+element/test_ndi_element.m.md'
        - filenavigator PACKAGE:
          - ndi.test.filenavigator.test_ndi_filenavigator: 'reference/+ndi/+test/+filenavigator/test_ndi_filenavigator.m.md'
          - ndi.test.filenavigator.test_ndi_filenavigator_fileIDfunction: 'reference/+ndi/+test/+filenavigator/test_ndi_filenavigator_fileIDfunction.m.md'
        - probe PACKAGE:
          - ndi.test.probe.test_ndi_probe: 'reference/+ndi/+test/+probe/test_ndi_probe.m.md'
        - session PACKAGE:
          - ndi.test.session.ndi_test_sessiontable: 'reference/+ndi/+test/+session/ndi_test_sessiontable.m.md'
        - setups PACKAGE:
          - ndi.test.setups.ndi_angeluccilab_test: 'reference/+ndi/+test/+setups/ndi_angeluccilab_test.m.md'
          - ndi.test.setups.ndi_katzlab_narendra_test: 'reference/+ndi/+test/+setups/ndi_katzlab_narendra_test.m.md'
          - ndi.test.setups.ndi_marderlab_hamood_test: 'reference/+ndi/+test/+setups/ndi_marderlab_hamood_test.m.md'
          - ndi.test.setups.ndi_testvhlabsetup: 'reference/+ndi/+test/+setups/ndi_testvhlabsetup.m.md'
        - testsuite PACKAGE:
          - ndi.test.testsuite.ndi_testsuite: 'reference/+ndi/+test/+testsuite/ndi_testsuite.m.md'
        - time PACKAGE:
          - ndi.test.time.filefind: 'reference/+ndi/+test/+time/filefind.m.md'
      - time PACKAGE:
        - ndi.time.clocktype: 'reference/+ndi/+time/clocktype.m.md'
        - ndi.time.syncgraph: 'reference/+ndi/+time/syncgraph.m.md'
        - ndi.time.syncrule: 'reference/+ndi/+time/syncrule.m.md'
        - ndi.time.timemapping: 'reference/+ndi/+time/timemapping.m.md'
        - ndi.time.timereference: 'reference/+ndi/+time/timereference.m.md'
        - ndi.time.timeseries: 'reference/+ndi/+time/timeseries.m.md'
        - syncrule PACKAGE:
          - ndi.time.syncrule.commontriggers: 'reference/+ndi/+time/+syncrule/commontriggers.m.md'
          - ndi.time.syncrule.filefind: 'reference/+ndi/+time/+syncrule/filefind.m.md'
          - ndi.time.syncrule.filematch: 'reference/+ndi/+time/+syncrule/filematch.m.md'
  - FAQ: 'faq.md'


use_directory_urls: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite


